# docker compose for swamp webserver
services:
  web:  
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-server-container # php apache container name here
    ports:
      - "80:80" # hosted on port 80
    networks:
      - web_db
    volumes:
      - "./app:/var/www/html" # mount volume4
    restart: unless-stopped
  db: # db for user login, auth, and preferences
    image: mysql:latest
    container_name: users-db # mysql container name here
    volumes:
      - "./db-data:/var/lib/mysql" # mount sql persistent data
      - "./initdb:/docker-entrypoint-initdb.d" # mount sql file to initdb.d
      - "./cnf/my.cnf:/etc/mysql/my.cnf" # mount my.cnf 
    env_file: .env # store passwords and other env vars here
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_DATABASE: web-users
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${USER_PWD}
    ports:
      - "3306:3306" # mysql server hosted on default port 
    networks:
      - web_db
    restart: unless-stopped
networks:
  web_db:
    external: false
