# docker compose for swamp webserver
services:
  web:  
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-server-container # php apache container name here
    ports:
      - "80:80" # hosted on port 80
    volumes:
      - "./app:/var/www/html" # mount volume4
    restart: unless-stopped
  db: # db for user login, auth, and preferences
    image: mysql:latest
    container_name: users-db # mysql container name here
    volumes:
      - "./app/sql:/var/lib/users-db" # mount sql files in container
      - "/path-to-sql-dump:/docker-entrypoint-initdb.d" # use sql dump backup to init db on container start
      - "/path-to-my.cnf/.my.cnf:/var/lib/.cnf/.my.cnf" # mount .my.cnf for passwordless auth
    environment:
      MYSQL_ROOT_PASSWORD: db-root-pwd
      MYSQL_DATABASE: web-users
      MYSQL_USER: db-agent
      MYSQL_PASSWORD: db-pwd
    ports:
      - "3306:3306" # mysql server hosted on default port 
    restart: unless-stopped
